// src/constants/apiEndpoints.ts

const BASE_URL = process.env.NEXT_PUBLIC_BASE_API_URL;
// Base URL : - https://mobileapp.parasinfotech.co.in/api/

export const API_ENDPOINTS = {
  GET_TOKEN: `${BASE_URL}sysfunction/gettokenmob`,
  CORPORATE_ID: `${BASE_URL}login/corporateid`,
  LOGIN_SYS: `${BASE_URL}login/login_sys`,
  REGISTER_DEVICE:`${BASE_URL}login/register_device`,
  GET_SALE_MAIN: `${BASE_URL}counter/get_sale_main`,
  DDDW_CRM_LIST: `${BASE_URL}counter/dddw_crm_list`,
  DDDW_USER_LIST: `${BASE_URL}counter/dddw_user_list`,
  ITEM_LIST: `${BASE_URL}counter/item_list`,
  ITEM_CATEGORY_MASTER_LIST: `${BASE_URL}counter/item_category_master_list`,
  COUNTER_LIST: `${BASE_URL}counter/counter_list`,
  CARET_LIST: `${BASE_URL}counter/caret_list`,
  GET_SALE_DETAIL: `${BASE_URL}counter/get_sale_detail`,
  BARCODE_MAIN: `${BASE_URL}counter/barcode_main`,
  BARCODE_DETAIL: `${BASE_URL}counter/barcode_detail`,
  GET_ITEMRATE: `${BASE_URL}counter/get_itemrate`,
  SALE_ADD: `${BASE_URL}counter/sale_add`,
  DELETE_SALE: `${BASE_URL}counter/sale_delete`,
  CRM_ADD: `${BASE_URL}counter/crm_add`,
  CRM_UPDATE: `${BASE_URL}counter/crm_update`,
  CRM_GROUP_LIST: `${BASE_URL}counter/crm_group_list`,
  GET_AZURE_TOKEN: `${BASE_URL}login/get_azure_token`,
  GET_CRM_DETAILS: `${BASE_URL}counter/get_crm`,
  DELETE_CRM: `${BASE_URL}counter/crm_delete`,
  GET_CODE: `${BASE_URL}counter/get_code`,
  ORDER_ADD: `${BASE_URL}counter/order_add`,
  GET_URD_MAIN: `${BASE_URL}counter/get_urd_main`,
  GET_URD_DETAIL: `${BASE_URL}counter/get_urd_detail`,
  DELETE_URD: `${BASE_URL}counter/urd_delete`,
  DELETE_ORDER: `${BASE_URL}counter/order_delete`,
  GET_ORDER_MAIN: `${BASE_URL}counter/get_order_main`,
  GET_ORDER_DETAIL: `${BASE_URL}counter/get_order_detail`,
  URD_ADD: `${BASE_URL}counter/urd_add`,
  GET_CLOSING_STOCK: `${BASE_URL}counter/closing_stock_get`,
  DELETE_CLOSING_STOCK: `${BASE_URL}counter/closing_stock_delete`,
  ADD_CLOSING_STOCK: `${BASE_URL}counter/closing_stock_add`,
  GET_USER_PROFILE: `${BASE_URL}SysFunction/get_user_profile`,
  SALE_REGISTER_ITEM: `${BASE_URL}report/sale_register_item`,
  BRANCH_LIST: `${BASE_URL}counter/branch_list`,
  GET_USER_LIST: `${BASE_URL}counter/get_user_list`,
  GET_ITEM_STOCK: `${BASE_URL}counter/get_item_stock`,
};
